services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [portfolio-site_default]

  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks: [portfolio-site_default]

  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks: [portfolio-site_default]

  kafka:
    image: bitnami/kafka:3.7
    depends_on: [zookeeper]
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    networks: [portfolio-site_default]

  shortener-svc:
    build:
      context: ./shortener-svc
      dockerfile: Dockerfile
    image: javaclaster-shortener-svc
    depends_on: [postgres, redis]
    networks: [portfolio-site_default]
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      APP_DB: ${APP_DB}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  redirect-svc:
    build:
      context: ./redirect-svc
      dockerfile: Dockerfile
    image: javaclaster-redirect-svc
    depends_on: [postgres, redis, kafka]
    networks: [portfolio-site_default]
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      APP_DB: ${APP_DB}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      KAFKA_BOOTSTRAP: ${KAFKA_BOOTSTRAP}

  analytics-svc:
    build:
      context: ./analytics-svc
    image: javaclaster-analytics-svc
    depends_on: [kafka, postgres]
    networks: [portfolio-site_default]
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      APP_DB: ${APP_DB}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      KAFKA_BOOTSTRAP: ${KAFKA_BOOTSTRAP}

networks:
  portfolio-site_default:
    external: true

volumes:
  pgdata:
