server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${APP_DB}
    username: ${APP_DB_USER}
    password: ${APP_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  base-url: https://go.vinch.uk
  cache-ttl-min: 60
