server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${APP_DB}
    username: ${APP_DB_USER}
    password: ${APP_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  base-url: https://u.vinch.uk
